# Generated by Django 5.2.5 on 2025-08-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="Унікальний ID користувача в Telegram", unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Назва підрядника або компанії", max_length=255
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Ім'я контактної особи",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Телефон підрядника",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email підрядника",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        help_text="Тип послуг, які надає підрядник (фотограф, ведучий, кейтеринг тощо)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата створення запису про підрядника",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата останнього оновлення запису про підрядника",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        help_text="Унікальний ID користувача в Telegram", unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username (наприклад, @username)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="Ім'я користувача",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Прізвище користувача",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Стан користувача для FSM (якщо використовується)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Чи активний користувач"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата створення користувача"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата останнього оновлення користувача"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(help_text="Назва події", max_length=255),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WEDDING", "Весілля"),
                            ("GENDER_PARTY", "Гендер-паті"),
                            ("ANNIVERSARY", "Річниця"),
                            ("FIRST_DATE", "Перше побачення"),
                            ("JUBILEE", "Ювілей"),
                            ("DATE", "Побачення"),
                        ],
                        help_text="Тип події (весілля, ювілей, побачення тощо)",
                        max_length=20,
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(help_text="Дата та час проведення події"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Місце проведення події",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Детальний опис події", null=True
                    ),
                ),
                (
                    "approx_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Орієнтовна кількість учасників",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Чи активна подія"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата створення події"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата останнього оновлення події"
                    ),
                ),
                (
                    "contractors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Підрядники, які беруть участь у події",
                        related_name="events",
                        to="app.contractor",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Замовники події",
                        related_name="events",
                        to="app.telegramuser",
                    ),
                ),
            ],
        ),
    ]
