# Generated by Django 5.2.5 on 2025-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="telegram_link",
            field=models.CharField(
                default="https://t.me/YourBot?start=TEMP", max_length=255
            ),
            preserve_default=False,
        ),
    ]
