# Generated by Django 5.2.5 on 2025-12-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_timing_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
