# Generated by Django 5.2.5 on 2025-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_event_event_timing_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_drive_guests_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_drive_photographer_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
